### ISSUE TITLE
Can't run on Nell dataset

### ISSUE THREAD

**Issue by LiZhang-github** [thu-ml/stochastic_gcn#1]
Hi, Jianfei. I read your paper and you reported the performance on Nell. I notice that you used data provided by Yang. I download Nell from Yang's GitHub [https://github.com/kimiyoung/planetoid](url). But when I run your program on Nell, it runs into a runtime error:
IndexError: index 42574 is out of bounds for axis 1 with size 8922.

So, I wonder if you do any other preprocessing of the  NELL dataset?
Thanks for your reply!

**Comment by cjf00000** [comment]
Hi LiZhang,

I think there are some data version issues but I cannot remember the details.

This is the dataset I used. Check if this works.
https://github.com/thu-ml/stochastic_gcn/releases/download/0.1/nell.tar.gz

**Comment by fansariadeh** [comment]
> Hi, Jianfei. I read your paper and you reported the performance on Nell. I notice that you used data provided by Yang. I download Nell from Yang's GitHub [https://github.com/kimiyoung/planetoid](url). But when I run your program on Nell, it runs into a runtime error:
> IndexError: index 42574 is out of bounds for axis 1 with size 8922.
> 
> So, I wonder if you do any other preprocessing of the NELL dataset?
> Thanks for your reply!

Hi there, I got the same issue as you. Could you please let me know if you solved it?
Many tanx and looking forward to hearing from you.
Cheers

**Comment by cjf00000** [comment]
Please try the dataset I provided above, and also make sure that your networkx version is correct.
* networkx (<=1.11 for loading GraphSAGE datasets)

I took the NELL script from the GraphSAGE repo. You may also check that if it does not work.
https://github.com/williamleif/GraphSAGE
